name: merge-to-branch
description: Merge to Branch
author: MoYummy
inputs:
  repo:
    required: true
    description: 'Repository'
    default: ${{ github.repository }}
  token:
    required: true
    description: Github Token
    default: ${{ github.token }}
  commit:
    required: true
    description: 'From Commit'
    default: ${{ github.sha }}
  branch:
    required: true
    description: 'To Branch'
    default: ${{ github.head_ref || github.ref }}
runs:
  using: 'node12'
  main: 'lib/index.js'
